export const plans = [
    {
        id: "be22d4a6-92f2-4a7f-9e10-1a1e0f0faaa1",
        name: "Free",
        currency:'$',
        price: 0,
        interval: "monthly",
        users: 1,
        customers: 5,
        description: "For individuals getting started",
        image: "/logo.svg",
        recommended: false,
        overview: ["1 user", "5 customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: false },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: false },
            { text: "Team Management", included: false },
            { text: "Integrations", included: false },
            { text: "Reports", included: false },
            { text: "Support: Community", included: true },
        ],
        stripe: {
            priceId: undefined,
            amount: 0,
            currency: "usd",
        },
    },
    {
        id: "1c6b99fc-0176-45b6-9f78-4b85e896e92a",
        name: "Free",
        currency:'$',
        price: 0,
        interval: "yearly",
        users: 1,
        customers: 5,
        description: "For individuals getting started",
        image: "/logo.svg",
        recommended: false,
        overview: ["1 user", "5 customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: false },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: false },
            { text: "Team Management", included: false },
            { text: "Integrations", included: false },
            { text: "Reports", included: false },
            { text: "Support: Community", included: true },
        ],
        stripe: {
            priceId: undefined,
            amount: 0,
            currency: "usd",
        },
    },
    {
        id: "2bca6e82-73c4-4fa1-9b92-c3c8cbebbb02",
        name: "Starter",
        currency:'$',
        price: 19,
        interval: "monthly",
        users: 3,
        customers: 50,
        description: "For freelancers & small teams",
        image: "/logo.svg",
        recommended: false,
        overview: ["3 users", "50 customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: true },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: true },
            { text: "Team Management", included: false },
            { text: "Integrations", included: true },
            { text: "Reports", included: true },
            { text: "Support: Standard", included: true },
        ],
        stripe: {
            priceId: process.env.NEXT_PUBLIC_STRIPE_STARTER_MONTHLY_PRICE_ID,
            amount: 1900,
            currency: "usd",
        },
    },
    {
        id: "96b83a43-cc34-4262-98c3-34a7eb87cc03",
        name: "Starter",
        currency:'$',
        price: 180,
        interval: "yearly",
        users: 3,
        customers: 50,
        description: "For freelancers & small teams",
        image: "/logo.svg",
        recommended: false,
        overview: ["3 users", "50 customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: true },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: true },
            { text: "Team Management", included: false },
            { text: "Integrations", included: true },
            { text: "Reports", included: true },
            { text: "Support: Standard", included: true },
        ],
        stripe: {
            priceId: process.env.NEXT_PUBLIC_STRIPE_STARTER_ANNUAL_PRICE_ID,
            amount: 1500,
            currency: "usd",
        },
    },
    {
        id: "382d6c5f-4a66-4d5b-b1d7-d14df54fc804",
        name: "Pro",
        currency:'$',
        price: 39,
        interval: "monthly",
        users: 10,
        customers: "Unlimited",
        description: "For growing businesses",
        image: "/logo.svg",
        recommended: true,
        overview: ["10 users", "Unlimited customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: true },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: true },
            { text: "Team Management", included: true },
            { text: "Integrations", included: true },
            { text: "Reports", included: true },
            { text: "Support: Priority", included: true },
        ],
        stripe: {
            priceId: process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID,
            amount: 3900,
            currency: "usd",
        },
    },
    {
        id: "ed027ea3-7e82-4d6b-ae21-d4c5c5cfe205",
        name: "Pro",
        currency:'$',
        price: 380,
        interval: "yearly",
        users: 10,
        customers: "Unlimited",
        description: "For growing businesses",
        image: "/logo.svg",
        recommended: true,
        overview: ["10 users", "Unlimited customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: true },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: true },
            { text: "Team Management", included: true },
            { text: "Integrations", included: true },
            { text: "Reports", included: true },
            { text: "Support: Priority", included: true },
        ],
        stripe: {
            priceId: process.env.NEXT_PUBLIC_STRIPE_PRO_ANNUAL_PRICE_ID,
            amount: 3200,
            currency: "usd",
        },
    },
    {
        id: "f11e5820-63ad-4ef9-9485-033e2d3a6a06",
        name: "Business",
        currency:'$',
        price: 79,
        interval: "monthly",
        users: 25,
        customers: "Unlimited",
        description: "For agencies & enterprises",
        image: "/logo.svg",
        recommended: false,
        overview: ["25 users", "Unlimited customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: true },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: true },
            { text: "Team Management", included: true },
            { text: "Integrations", included: true },
            { text: "Reports", included: true },
            { text: "Support: 24/7", included: true },
        ],
        stripe: {
            priceId: process.env.NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PRICE_ID,
            amount: 7900,
            currency: "usd",
        },
    },
    {
        id: "9a8f1de4-f1e1-47a7-934e-93e32f789e07",
        name: "Business",
        currency:'$',
        price: 780,
        interval: "yearly",
        users: 25,
        customers: "Unlimited",
        description: "For agencies & enterprises",
        image: "/logo.svg",
        recommended: false,
        overview: ["25 users", "Unlimited customers"],
        highlights: [
            { text: "Automated Invoicing", included: true },
            { text: "Secure Payments", included: true },
            { text: "Real-Time Analytics", included: true },
            { text: "Customer Management", included: true },
            { text: "Fast Onboarding", included: true },
            { text: "Subscription Management", included: true },
            { text: "Team Management", included: true },
            { text: "Integrations", included: true },
            { text: "Reports", included: true },
            { text: "Support: 24/7", included: true },
        ],
        stripe: {
            priceId: process.env.NEXT_PUBLIC_STRIPE_BUSINESS_ANNUAL_PRICE_ID,
            amount: 6500,
            currency: "usd",
        },
    },
];
